### ISSUE TITLE
Версия Стандарт

### ISSUE THREAD

**Issue by ProklUng** [avshatalov48/bitrix-core-business#1]
Добрый день. А можно ли сделать такую же штуку, но для версии Битрикс Стандарт? Было бы очень здорово.

**Comment by avshatalov48** [comment]
> Добрый день. А можно ли сделать такую же штуку, но для версии Битрикс Стандарт? Было бы очень здорово.

Здравствуйте!

Версия "Бизнес" уже содержит все модули редакций "Старт", "Стандарт", "Малый бизнес". По факту, в младших редакциях, отсутствуют модули из старших, всё остальное одинаково.

Для разработки, лучше иметь максимальную редакцию, по предложенной инструкции, все необходимые классы будут найдены. Опять же, всё в 1 месте, меньше занимает места, IDE проще индексировать.

Опять же, тогда необходимо будет создать также отдельные репозитории и для остальных редакций.

Пока не представляю, для каких кейсов это может потребоваться. А лишние модули можно всегда удалить.

**Comment by ProklUng** [comment]
Да, резонные соображения. Спасибо за подробный ответ.
