### ISSUE TITLE
Последующие обновления

### ISSUE THREAD

**Issue by LeTraceurSnork** [avshatalov48/bitrix-core-business#4]
Заранее спасибо за титанический труд!
Подскажите, планируется ли продолжение работы над пакетом? У Битрикса в январе вышло новое мажорное обновление v24.0.0 и все его последующие версии (последняя v24.200.200) - будут ли они добавлены?

**Comment by avshatalov48** [comment]
@LeTraceurSnork доброго времени суток! Работа будет продолжена, обновления будут добавляться.

**Comment by avshatalov48** [comment]
Обновлено до версии 24.200.200
